package com.fileshareappv1.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionAllPropertiesEquals(Reaction expected, Reaction actual) {
        assertReactionAutoGeneratedPropertiesEquals(expected, actual);
        assertReactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionAllUpdatablePropertiesEquals(Reaction expected, Reaction actual) {
        assertReactionUpdatableFieldsEquals(expected, actual);
        assertReactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionAutoGeneratedPropertiesEquals(Reaction expected, Reaction actual) {
        assertThat(actual)
            .as("Verify Reaction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionUpdatableFieldsEquals(Reaction expected, Reaction actual) {
        assertThat(actual)
            .as("Verify Reaction relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getReactedAt()).as("check reactedAt").isEqualTo(expected.getReactedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactionUpdatableRelationshipsEquals(Reaction expected, Reaction actual) {
        assertThat(actual)
            .as("Verify Reaction relationships")
            .satisfies(a -> assertThat(a.getPost()).as("check post").isEqualTo(expected.getPost()));
    }
}
