package com.fileshareappv1.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShareAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShareAllPropertiesEquals(Share expected, Share actual) {
        assertShareAutoGeneratedPropertiesEquals(expected, actual);
        assertShareAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShareAllUpdatablePropertiesEquals(Share expected, Share actual) {
        assertShareUpdatableFieldsEquals(expected, actual);
        assertShareUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShareAutoGeneratedPropertiesEquals(Share expected, Share actual) {
        assertThat(actual)
            .as("Verify Share auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShareUpdatableFieldsEquals(Share expected, Share actual) {
        assertThat(actual)
            .as("Verify Share relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShareUpdatableRelationshipsEquals(Share expected, Share actual) {
        assertThat(actual)
            .as("Verify Share relationships")
            .satisfies(a -> assertThat(a.getPost()).as("check post").isEqualTo(expected.getPost()));
    }
}
