name: CI/CD Pipeline

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: mvn test -Pprod

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
      - name: Deploy on server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/project/file_share_app_v1
            git pull
            ./mvnw clean verify -Pprod jib:dockerBuild -DskipTests
            cd ~/project/file_share_app_v1/docker-compose
            docker compose build
            docker compose up -d --remove-orphans
          EOF
